site_name: Gutenbit
site_description: Download, parse, and search Project Gutenberg texts in SQLite.

repo_name: Gutenbit

theme:
  name: material
  language: en
  palette:
    - scheme: default
      primary: custom
      accent: custom
  features:
    - navigation.sections
    - content.code.copy

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - mkdocstrings:
      handlers:
        python:
          options:
            filters:
              - "!^_"
            merge_init_into_class: true
            show_root_heading: true
            show_root_full_path: false
            show_signature_annotations: true
            show_source: false

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences

nav:
  - Home: index.md
  - Quickstart: quickstart.md
  - CLI: cli.md
  - API Reference: reference/
