"""Re-exports from gutenbit.cli._display for backward compatibility."""

# ruff: noqa: F401
from gutenbit.cli._display import (
    BOOK_ID_KEY,
    BOOK_ID_LABEL,
    EMPTY_DISPLAY,
    FOOTER_TITLE_MAX_CHARS,
    TOC_OPENING_PREVIEW_CHARS,
    TOC_OVERVIEW_LIST_MAX_ITEMS,
    TOC_SECTION_MAX_CHARS,
    CliDisplay,
    _compact_section_label,
    _display_read,
    _display_text,
    _display_words,
    _footer_book_id,
    _footer_title,
    _IngestProgressSession,
    _is_tty,
    _passage_footer_stats,
    _passage_header,
    _plural,
    _print_key_value_table,
    _print_table,
    _ratio_summary,
    _section_label,
    _section_meta_bits,
    _section_summary_stats,
    _section_visibility_summary,
    _toc_rows,
    _toc_section_label,
    _toc_separator,
    _toc_widths,
    _TocRow,
    _truncate_single_line,
    format_search_footer_stats,
    format_search_summary_count,
    format_summary_stats,
)
